//Crie um programa que exiba uma mensagem de boas-vindas ao usuário.//

function boasVindas(){
    console.log("Boas-Vindas")
}
boasVindas()

//Crie um programa que faça a soma de dois números//
function somarNumeros(){
let y = 2 , x = 2 , soma = x + y
console.log(soma)
}
somarNumeros()

//Crie um programa que exiba a subtração de dois números//
function subtrairNumeros(){
let y = 2 , x = 4 , sub = x - y
console.log(sub)
}
subtrairNumeros()

//Crie um programa que exiba a multiplicação de dois números//
function multiNumeros(){
let y = 2 , x = 4 , multi = x * y
console.log(multi)
}
multiNumeros()

//Crie um programa que exiba a divisão de dois números//
function dividirNumeros(){
let y = 2 , x = 4 , dividir = x / y
console.log(dividir)
}
dividirNumeros()

//Crie um programa que calcule a média de três números.//
function mediaNumeros(){
let y = 10 , x = 9 , z = 10
media= (x+y+z) / 3
console.log(media)
}
mediaNumeros()

